version: '3.8'

services:
    grpc-server:
        build:
            context: ./go
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - internal_net

    grpc-client:
        build:
            context: ./python
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        restart: always
        depends_on:
            - grpc-server
            - redis
        networks:
            - internal_net
            - public_net

    redis:
        image: redis:latest
        container_name: redis_service
        restart: always
        networks:
            - internal_net

networks:
    internal_net:
        driver: bridge
    public_net:
        driver: bridge
