version: '3.8'

services:
    grpc-server:
        build:
            context: ./go
            dockerfile: Dockerfile
        # ports:
        #     - '44044:44044'
        restart: unless-stopped
        expose:
            - '44044'
        networks:
            - internal_net

    grpc-client:
        build:
            context: ./python
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        volumes:
            - .:/app
        restart: always
        depends_on:
            - grpc-server
        networks:
            - internal_net

networks:
    internal_net:
        driver: bridge
