app:
    id: 1
    name: 'test'
    secret: 'test-app'
    host: '0.0.0.0'
    port: 8000

database:
    url: 'sqlite:///./app.db'

redis:
    host: 'redis'
    port: 6379

grpc:
    host: 'grpc-server'
    port: 44044
